import P from 'prop-types';
import { AppProps } from 'next/app';
import { Inter } from 'next/font/google';
import StyledComponentsRegistry from '../lib/registry';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}

RootLayout.propTypes = AppProps;
