"use client"
import { Inter } from 'next/font/google'
import StyledComponentsRegistry from '../lib/registry'
import {theme} from '../styles/themes';
import {ThemeProvider} from 'styled-components'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}> <StyledComponentsRegistry> <ThemeProvider theme={theme}>{children}</ThemeProvider></StyledComponentsRegistry></body>
    </html>
  )
}
